### ISSUE TITLE
https://web-push-codelab.appspot.com/   now is 404 not found

### ISSUE THREAD

**Issue by randybrutal** [GoogleChromeLabs/web-push-codelab#51]
Yesterday this site still can open, 
but today is 404 not found, please fix it.
Thanks very much!!

**Comment by samdutton** [comment]
@gauntface fyi

**Comment by Lenewtype** [comment]
https://web-push-codelab.glitch.me/

**Comment by randybrutal** [comment]
Thank you very much!

**Comment by samdutton** [comment]
Thanks Nick!

**Comment by gauntface** [comment]
I've updated the codelab, just waiting on web fundamentals.
