### ISSUE TITLE
Links to web-push-codelab.appspot.com are dead. 

### ISSUE THREAD

**Issue by kyro38** [GoogleChromeLabs/web-push-codelab#56]
The 2 tools hosted on https://web-push-codelab.appspot.com/ aren't accessible anymore.

**Comment by gauntface** [comment]
Moved here: https://web-push-codelab.glitch.me/

**Comment by kyro38** [comment]
https://developers.google.com/web/fundamentals/codelabs/push-notifications/ probably needs to be updated !

**Comment by gauntface** [comment]
@kyro38 trust me, I've been nagging.
