### ISSUE TITLE
Links to 404

### ISSUE THREAD

**Issue by sharpless512** [GoogleChromeLabs/web-push-codelab#59]
"To simplify things for this code lab copy the following details into the Push Companion Site"
![image](https://user-images.githubusercontent.com/2988809/31538083-b86ff45e-b004-11e7-8c28-0feceacc3409.png)

When you click on that links it goes to https://web-push-codelab.appspot.com/ , which does not exist

**Comment by gauntface** [comment]
Thanks for raising the issue @sharpless512 and sorry I missed it in the codelab itself.
